# Server settings
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Database settings
database:
  # The name of your JDBC driver, for MySQL it's this.
  driverClass: com.mysql.cj.jdbc.Driver
  # The database user and password.
#  user: root
#  password: "AhF1eik4!@#%"
#  # The JDBC URL for your database. You may need to adjust the port and database name.
#  url: jdbc:mysql://localhost:3306/lms?useSSL=false&serverTimezone=UTC
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_URL}
  # Dropwizard's built-in connection pool settings
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level: INFO
  loggers:
    org.example: DEBUG
    org.jdbi: INFO